<#
.SYNOPSIS
    Shared theme, helpers, and prerequisite checks for the Rance Timber AD Toolkit.

.DESCRIPTION
    Dot-sourced by ADToolkit.ps1 before any feature scripts load. This file only defines
    variables and functions - it doesn't do anything on its own, so there's no need to run
    it directly.

    Every feature script (Functions\Invoke-*.ps1) can rely on everything in here already
    being loaded: the $Theme colour palette, the shared HTML CSS block, Test-ADModuleAvailable,
    Show-Banner, Show-BorderedTable, and Wait-KeyPress.

.NOTES
    Author       : Jeremy
    Date Created : 2026-08-11
    Part of      : Rance Timber AD Toolkit
#>

# ===== SHARED COLOUR THEME =====
# Every screen in the toolkit (menu + individual feature reports) pulls colours from here so
# the whole thing looks consistent. Add new keys as needed - don't hardcode colour names
# inside feature scripts, reference $Theme.XXX instead.
$Theme = @{
    Title   = 'Cyan'
    Accent  = 'Magenta'
    Text    = 'White'
    Muted   = 'DarkGray'
    Warn    = 'Yellow'
    Error   = 'Red'
    Success = 'Green'
}

# Shared CSS so every HTML report generated by any feature in the toolkit looks the same.
# Feature scripts embed this inside their own <style> block, e.g. "<style>$HtmlThemeStyle</style>".
$HtmlThemeStyle = @"
    body { background-color: #0C0C0C; color: #CCCCCC; font-family: Consolas, 'Courier New', monospace; padding: 30px; }
    h1 { color: #61D6D6; border-bottom: 2px solid #61D6D6; padding-bottom: 8px; }
    .meta p { margin: 4px 0; }
    .meta span.label { display: inline-block; width: 150px; }
    .found { color: #F9F1A5; font-weight: bold; margin-top: 20px; margin-bottom: 6px; }
    table { border-collapse: collapse; width: 100%; margin-top: 10px; }
    th, td { border: 1px solid #444; padding: 6px 10px; text-align: left; font-size: 13px; }
    th { background-color: #1a1a1a; color: #61D6D6; }
    td.center, th.center { text-align: center; }
    tr.privileged { background-color: #3a1414; color: #ff8080; }
    tr.never-expires { background-color: #332b00; color: #f9f1a5; }
    .legend { margin-top: 15px; font-size: 12px; color: #999; }
    .legend span.item { display: inline-block; margin-right: 20px; }
    .legend .swatch { display: inline-block; width: 12px; height: 12px; margin-right: 6px; vertical-align: middle; }
"@

# Confirms the ActiveDirectory module is available and imports it. Safe to call repeatedly -
# every feature script should call this itself too, so it still works if dot-sourced directly
# without going through the menu.
function Test-ADModuleAvailable {
    if (-not (Get-Module -ListAvailable -Name ActiveDirectory)) {
        return $false
    }
    Import-Module ActiveDirectory -ErrorAction Stop
    return $true
}

# Draws a boxed title banner using the shared theme. Used for the main menu header; feature
# scripts are free to reuse it too for their own screens.
function Show-Banner {
    param(
        [Parameter(Mandatory = $true)][string]$Text,
        [string]$Color = $Theme.Title
    )
    $Width = $Text.Length + 4
    Write-Host ('+' + ('-' * $Width) + '+') -ForegroundColor $Color
    Write-Host ('|  ' + $Text + '  |') -ForegroundColor $Color
    Write-Host ('+' + ('-' * $Width) + '+') -ForegroundColor $Color
}

# Renders a PSCustomObject array as a table with vertical divider lines between columns.
# -CenterColumns lets specific columns be centre-aligned instead of the default left-align.
# Shared by any feature script that needs bordered tabular console output.
function Show-BorderedTable {
    param(
        [Parameter(Mandatory = $true)][object[]]$InputObject,
        [Parameter(Mandatory = $true)][string[]]$Columns,
        [string[]]$CenterColumns = @()
    )

    if (-not $InputObject -or $InputObject.Count -eq 0) { return }

    $Widths = @{}
    foreach ($Col in $Columns) {
        $MaxValueLen = ($InputObject | ForEach-Object { "$($_.$Col)".Length } | Measure-Object -Maximum).Maximum
        $Widths[$Col] = [Math]::Max($Col.Length, $MaxValueLen)
    }

    $HeaderParts = foreach ($Col in $Columns) { $Col.PadRight($Widths[$Col]) }
    Write-Host ($HeaderParts -join ' | ')

    $SepParts = foreach ($Col in $Columns) { '-' * $Widths[$Col] }
    Write-Host ($SepParts -join '-+-')

    foreach ($Row in $InputObject) {
        $RowParts = foreach ($Col in $Columns) {
            $Value = "$($Row.$Col)"
            if ($CenterColumns -contains $Col) {
                $Pad   = $Widths[$Col] - $Value.Length
                $Left  = [Math]::Floor($Pad / 2)
                $Right = $Pad - $Left
                (' ' * $Left) + $Value + (' ' * $Right)
            }
            else {
                $Value.PadRight($Widths[$Col])
            }
        }
        Write-Host ($RowParts -join ' | ')
    }
}

# Pauses and waits for a keypress before returning to the menu. Falls back to Read-Host on
# hosts that don't support [Console]::ReadKey (e.g. some ISE configurations).
function Wait-KeyPress {
    param([string]$Message = 'Press any key to return to the menu...')
    Write-Host ''
    Write-Host $Message -ForegroundColor $Theme.Muted
    try {
        [void][System.Console]::ReadKey($true)
    }
    catch {
        Read-Host | Out-Null
    }
}
